### PR TITLE
Fix compiler error in webshop example

### PR DESCRIPTION
**Pull request by andywhite37**
- Fix webshop example compile-time error
- Also fix a small typo in README.md

### CODE REVIEW

**Comment by ciscoheat** [comment]
Thank you! Actually with the latest version (of both Mithril itself and this library) you don't need `Module` when only using `view()` anymore, so can you try to upgrade to the latest and see if it works?

**Comment by andypellucid** [comment]
Hmm, interesting.  Yeah, I just installed everything today, I currently have mithril-hx version 0.20.1 from haxelib, and the webshop example appears to be referencing mithril.min.js version 0.1.30, which I think is the latest.

When I try to compile, I get this:

```
[awhite@acw][~/dev/ciscoheat/mithril-hx][git:master][4996][0]>>> haxe webshop.hxml
example/webshop/Webshop.hx:31: lines 31-36 : webshop.Webshop should be mithril.MithrilModule<Dynamic>
example/webshop/Webshop.hx:31: lines 31-36 : webshop.Webshop should be { view : ?ctrl : Dynamic -> mithril.ViewOutput, controller : Void -> Dynamic }
example/webshop/Webshop.hx:31: lines 31-36 : webshop.Webshop has no field controller
```

**Comment by ciscoheat** [comment]
Yes, very interesting. It works for me, and I'm testing now with 0.20.1 directly from haxelib. Can you check `M.hx` in your haxelib for the `View` interface? https://github.com/ciscoheat/mithril-hx/blob/master/src/mithril/M.hx#L23-L25

It should be used in the `Webshop` class: https://github.com/ciscoheat/mithril-hx/blob/master/example/webshop/Webshop.hx#L13

When you have patched `Webshop` as in this pull request, does [Search.hx](https://github.com/ciscoheat/mithril-hx/blob/master/example/webshop/Search.hx#L12) still compile? That would be very interesting since it's also a `View` without Type Parameters.

@fponticelli also mentioned this problem, is it exactly the same for you?

**Comment by fponticelli** [comment]
Yes, me and Andy work together and we stared at the same problem on the same monitor :)

**Comment by andywhite37** [comment]
Thanks for the reply!  And, by the way, excellent work on this project, it's really nice so far!  Also, I'm working with @fponticelli, I asked him about the error, and he said he could reach out to you directly, so that's why he was asking.

So, I think the problem is with the version of haxe I'm using.  I currently have the haxe master version 3.2.0 (from `brew install haxe --HEAD`).  I tried running the stable haxe 3.1.3, and the webshop.hxml built successfully.

It seems there is something funny with the `var routes = Dynamic<MithrilModule<Dynamic>>;` in Webshop.hx.

```haxe
// In M.hx:
typedef MithrilModule<T> = {
	function controller() : T;
	function view(?ctrl : T) : ViewOutput;
}
```

I'm not sure, but itt seems like that should constrain the values of `routes` to be `MithrilModule<Dynamic>`, but when you assign routes:

```haxe
        routes = {
            "/": this,
            "/category/:categoryId": productList,
            "/product/:productId": productPage,
            "/checkout": checkout
        };
```

`this` is not a `MithrilModule<Dynamic>`?  That's about as far as I got.

**Comment by ciscoheat** [comment]
Ah, that could be it! And it makes sense, because the definition of a Mithril module has been relaxed to basically any object, and the latest compiler probably detects that `routes` aren't constrained to `MithrilModule` anymore.

This means that routes should be `Dynamic` now. I'll change that and make an update.

**Comment by ciscoheat** [comment]
Version 0.20.2 is now available that uses Dynamic for routes. If you can test and confirm that it works, it would be great.

**Comment by andywhite37** [comment]
Nice!  That fixed it, thanks for looking into this.  I'll close the PR.

**Comment by ciscoheat** [comment]
Great, thank you too! I've made a few other fixes on the webshop project as well, in case you want to merge.

**Pull request closed without merging**
